---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: macao-recommender
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macao-recommender-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - serviceaccounts
      - events
      - configmaps
      - secrets
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
      - verticalpodautoscalercheckpoints
      - verticalpodautoscalers/status
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: macao-recommender-binding
subjects:
  - kind: ServiceAccount
    name: macao-recommender
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: macao-recommender-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recommender-config
  namespace: kube-system
data:
  "recommender_config.yaml": |
    DEFAULT_NAMESPACE: "default"
    PROMETHEUS_URL: "http://prometheus-server.monitoring.svc.cluster.local:80"
    ENABLED_PLOTTING: false
    RECOMMENDER_INTERVAL: 60
    PLOT_TIME_RANGE: "1h"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macao-recommender
  namespace: kube-system
  labels:
    app: macao-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: macao-recommender
  template:
    metadata:
      labels:
        app: macao-recommender
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: macao-recommender
      containers:
        - name: macao-recommender
          image: quay.io/macao/shift-week-03-24-25:latest
          imagePullPolicy: Always
          tty: true
          stdin: true
          resources:
            limits:
              cpu: "1"
              memory: "400Mi"
          volumeMounts:
            - name: recommender-config
              mountPath: /app/config
      volumes:
        - name: recommender-config
          configMap:
            name: recommender-config
